apiVersion: v1
kind: Service
metadata:
  name: flask-test-service
spec:
  selector:
    app: flask-test-app1
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-app1
spec:
  selector:
    matchLabels:
      app: flask-test-app1
  replicas: 5
  template:
    metadata:
      labels:
        app: flask-test-app1
    spec:
      containers:
      - name: flask-test-flask-test-app1
        image: mypoc
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080